### ISSUE TITLE
Unicef organization under "Distance"?

### ISSUE THREAD

**Issue by lkysow** [PeaceGeeksSociety/services-advisor#151]
@tuckerbuchy @cynthialee do you guys know why Unicef is listed under distance in the filters?

![image](https://cloud.githubusercontent.com/assets/1034429/8869157/812b1fea-3195-11e5-9366-f07a1433c559.png)

**Comment by cynthialee** [comment]
That's a placeholder. It means that no one has implemented it or tied it
into the filter UI.

**Comment by lkysow** [comment]
Okay so if we don't do distance we can remove this section?

**Comment by PeaceGeeks** [comment]
Hey Luke - this appears on the original app. I am not entirely clear why it was left out. How much effort would it be to include these filters

We have province so that is probably good for now, but this is what it looked like in the original app
![screen shot 2015-07-24 at 1 32 33 pm](https://cloud.githubusercontent.com/assets/2263033/8879566/90d3ad40-3208-11e5-8fe7-020668285ed3.png)

**Comment by lkysow** [comment]
Yes I know but we must cut all non essential features.

**Comment by PeaceGeeks** [comment]
Ok I agree this is non-essential for now. I have created a separate ticket for this issue anyway, so we can close that, and look at this in a future release.
