### ISSUE TITLE
Referral Filter not behaving as expected

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#159]
'Does not require referral' should return all records that have Referral Method = either 'Referral Not Accepted' OR 'Referral is Not Required'

instead, it displays 2 'Referral Method' = 'unknows' and 1 no value

**Comment by lkysow** [comment]
@PeaceGeeks see my comment on #89 

> Okay so here's what I've done:
> 
> any service marked "Referrals not accepted" or "Referral is not required" or not given a referral status is considered Referral not required
> any service marked otherwise, ex. "Email on a per case basis", "IA Form", "Telephone on a per case basis", "RAIS", is considered Referral required
> I created 3 radio buttons: All, Referral Required, Referral Not Required. It turns out there's only 3 services where referrals are not required so it doesn't make sense to default to that, therefore I've defaulted to All

The reason you're not seeing any other type of referral method is because there are no services with that type that are not past their dates. This should be closed.

**Comment by PeaceGeeks** [comment]
HI @lkysow - the problem is this: 

for the 3 records that return, NONE have a Referral Method = "Referrals not accepted" or "Referral is not required" - just 3 with nothing at all, but I can also see a bunch of records that should be displaying in Referral not Required - here are some examples (see Referral Method)

http://dev.pgunhcr.peacegeeks.org/#/services/2039902216
http://dev.pgunhcr.peacegeeks.org/#/services/1817791684
http://dev.pgunhcr.peacegeeks.org/#/services/646297324

**Comment by lkysow** [comment]
Okay I see a bug. Will fix after work.

**Comment by lkysow** [comment]
Looks good now.

**Comment by PeaceGeeks** [comment]
Am still seeing some 'Referrals Not Accepted' records appearing when the 'Referral Required' filter is selected. Here are some examples. http://dev.pgunhcr.peacegeeks.org/#/services/1852170347
http://dev.pgunhcr.peacegeeks.org/#/services/1914605032

**Comment by lkysow** [comment]
There's still an issue with selecting a filter and then selecting another category, I think that's how you saw this record because when I do a filter immediately upon load I only see one service in that region that your first service is in.

With filter referral required:
![image](https://cloud.githubusercontent.com/assets/1034429/9149593/1eaeba7a-3d66-11e5-8c29-c07de80864d6.png)

With filter referral not required, your service is the bottom one:
![image](https://cloud.githubusercontent.com/assets/1034429/9149596/436e4524-3d66-11e5-9648-ce8611328632.png)

I believe the filtering works initially but you ran into another bug with it not working after subsequent actions. That bug is being addressed. Can you reproduce this by reloading the page, selecting a filter, and then clicking on a single map icon?

**Comment by PeaceGeeks** [comment]
These are the steps I follow:
1. Filter on  'Referral Required'
2. Go to Cash 
3. Go to Financial Assistance
4. Choose the 6th record down - Tafileh Governorate: Financial Assistance
http://dev.pgunhcr.peacegeeks.org/#/services/1852170347

**Comment by lkysow** [comment]
Yes this was caused because the filtering on referral didn't work with category search. @tuckerbuchy fixed this, I cannot reproduce anymore.
