### ISSUE TITLE
UNHCR style

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#96]
Hi @Edouard-Legoupil and @PeaceGeeks 

Just a thought, I originally designed the app with its own style, but I am realizing that the original colours chosen reflected the http://help.unhcr.jo/ site. Do you want to change the colours of the Services Advisor to better match those colours?

![desktop-search-results-detail_oldcolours](https://cloud.githubusercontent.com/assets/5739342/8265890/0934a796-16c3-11e5-998a-bb65011fbed9.png)

**Comment by PeaceGeeks** [comment]
HI @Amy - that site will likely eventually disappear because we are proposing to integrate the Services Advisor piece into a broader app called MyUNHCR. If anything, I would say go with those colors. I quite like the colors you chose, but the blue might make sense. Also (and I recognize this is partly a font issue), I have a hard time reading the red. 

On the other hand, the Email/ Print idea is a great one. Is that in the design the guys are working with?

**Comment by amyngai** [comment]
That was an older idea - not MVP at the moment (lots of things to finish first!). :P. Perhaps for a V2 :)

closing this issue and keeping the colours!
